version: '3.8'

services:
  komiix-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - CORS_ORIGINS=${CORS_ORIGINS}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - COMPOSE_BAKE=${COMPOSE_BAKE}
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    networks:
      - komiix-network
    depends_on:
      - libretranslate
      - redis

  libretranslate:
    build:
      context: ./libretranslate
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=${LT_LOAD_ONLY:-es,ja,zh,ko,en}
      - LT_PACKAGE_DIR=/app/models
    networks:
      - komiix-network
    volumes:
      - libretranslate_models:/app/models
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - komiix-network

  komiix-frontend:
    build:
      context: ./frontend
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: komiix
    environment:
      - COMPOSE_BAKE=${COMPOSE_BAKE}
    networks:
      - komiix-network

networks:
  komiix-network:
    driver: bridge

volumes:
  libretranslate_models: