services:
  komiix-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - paddle_models:/root/.paddlex/official_models
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - CORS_ORIGINS=${CORS_ORIGINS}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - COMPOSE_BAKE=${COMPOSE_BAKE}
      - LIBRETRANSLATE_URL=${LIBRETRANSLATE_URL}
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    networks:
      - komiix-network
    depends_on:
      - libretranslate
      - redis

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    volumes:
      - libretranslate_models:/home/libretranslate/.local
    environment:
      - LT_LOAD_ONLY=es,en,zh-Hans,ko,ja
    networks:
      - komiix-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - komiix-network

  komiix-frontend:
    build:
      context: ./frontend
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_KOMIIX_BACKEND_URL=${VITE_KOMIIX_BACKEND_URL}
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: komiix
    environment:
      - COMPOSE_BAKE=${COMPOSE_BAKE}
    networks:
      - komiix-network

networks:
  komiix-network:
    driver: bridge

volumes:
  libretranslate_models:
  paddle_models:
